# Generated by Django 5.2.16 on 2026-07-12 18:27

import contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=240)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('responses', models.JSONField(default=dict)),
                ('final_body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('partial', 'Parcial'), ('signed', 'Assinado'), ('cancelled', 'Cancelado')], default='draft', max_length=10)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.contracttemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Vencido')], default='pending', max_length=10)),
                ('pix_txid', models.CharField(max_length=64, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('contact', models.CharField(max_length=160)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('viewed', 'Visualizou'), ('verified', 'Verificou'), ('signed', 'Assinou')], default='pending', max_length=10)),
                ('token', models.CharField(default=contracts.models.signing_token, editable=False, max_length=64, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='contracts.contract')),
            ],
            options={
                'ordering': ['signing_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SignatureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('viewed', 'Visualizou'), ('verified', 'Verificou'), ('signed', 'Assinou')], max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='contracts.party')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField()),
                ('simple_explanation', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contracttemplate')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('template', 'key'), name='unique_template_clause')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('text', models.CharField(max_length=240)),
                ('type', models.CharField(choices=[('text', 'text'), ('value', 'value'), ('date', 'date'), ('option', 'option'), ('bool', 'bool'), ('number', 'number'), ('textarea', 'textarea')], max_length=12)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField()),
                ('display_condition', models.JSONField(blank=True, default=dict)),
                ('required', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=240)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contracts.contracttemplate')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('template', 'key'), name='unique_template_question')],
            },
        ),
    ]
