# Generated by Django 5.2.16 on 2026-07-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contracttemplate_contract_installment_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='verification_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
